"""Initialization

Revision ID: 555b4d27aa49
Revises: 
Create Date: 2024-11-14 20:19:41.719345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '555b4d27aa49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'currency',
                    existing_type=postgresql.ENUM('byn', 'usd', 'rub', 'eur', name='moneycurrency'),
                    type_=sa.Enum('byn', 'usd', 'rub', 'eur', name='moneycurrency'),
                    existing_nullable=False,
                    postgresql_using="currency::text::moneycurrency")
    op.alter_column('users', 'language_code',
                    existing_type=postgresql.ENUM('ru', 'en', name='LanguageCodesEnum'),
                    type_=sa.Enum('ru', 'en', name='LanguageCodesEnum'),
                    existing_nullable=True,
                    postgresql_using="language_code::text::LanguageCodesEnum")
    op.alter_column('users', 'money_currency',
                    existing_type=postgresql.ENUM('byn', 'usd', 'rub', 'eur', name='moneycurrency'),
                    type_=sa.Enum('byn', 'usd', 'rub', 'eur', name='moneycurrency'),
                    existing_nullable=True,
                    postgresql_using="money_currency::text::moneycurrency")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'money_currency',
                    existing_type=sa.Enum('byn', 'usd', 'rub', 'eur', name='moneycurrency'),
                    type_=postgresql.ENUM('byn', 'usd', 'rub', 'eur', name='money_currency'),
                    existing_nullable=True)
    op.alter_column('users', 'language_code',
                    existing_type=sa.Enum('ru', 'en', name='LanguageCodesEnum'),
                    type_=postgresql.ENUM('ru', 'en', name='language_code'),
                    existing_nullable=True)
    op.alter_column('categories', 'currency',
                    existing_type=sa.Enum('byn', 'usd', 'rub', 'eur', name='moneycurrency'),
                    type_=postgresql.ENUM('byn', 'usd', 'rub', 'eur', name='money_currency'),
                    existing_nullable=False)
    # ### end Alembic commands ###
