"""Updated config_date

Revision ID: adc98f5fc406
Revises: 055a5c5a94bd
Create Date: 2024-11-23 22:05:25.466779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'adc98f5fc406'
down_revision: Union[str, None] = '055a5c5a94bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_timestamps', sa.Column('config_date', sa.String(), server_default=sa.text(
        "concat(EXTRACT(doy FROM now()), '.', EXTRACT(week FROM now()), '.', EXTRACT(month FROM now()), '.', EXTRACT(quarter FROM now()), '.', CASE WHEN (EXTRACT(quarter FROM now()) < 3) THEN 1 ELSE 2 END, '.', EXTRACT(year FROM now()))"),
                                                   nullable=False))
    op.alter_column('category_timestamps', 'category_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint(None, 'category_timestamps', ['id'])
    op.drop_column('category_timestamps', 'day_week_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_timestamps', sa.Column('day_week_month', sa.VARCHAR(), server_default=sa.text(
        "concat(EXTRACT(doy FROM now()), '.', EXTRACT(week FROM now()), '.', EXTRACT(month FROM now()))"),
                                                   autoincrement=False, nullable=False))
    op.drop_constraint(None, 'category_timestamps', type_='unique')
    op.alter_column('category_timestamps', 'category_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('category_timestamps', 'config_date')
    # ### end Alembic commands ###
