"""Rename and refactoring timestampts

Revision ID: 9eed4518f257
Revises: bf1200ca4a10
Create Date: 2024-11-17 17:09:30.020652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eed4518f257'
down_revision: Union[str, None] = 'bf1200ca4a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories',
                  sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('categories', 'timestamp')
    op.alter_column('users', 'joined_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'joined_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.add_column('categories',
                  sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False,
                            nullable=True))
    op.drop_column('categories', 'created_date')
    # ### end Alembic commands ###
