"""modify table_args in Category Model

Revision ID: b7f61cd3b5ca
Revises: 9df2ae568c9f
Create Date: 2024-12-05 20:05:35.580110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f61cd3b5ca'
down_revision: Union[str, None] = '9df2ae568c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('title_user_id_field', 'categories', ['title', 'user_id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint('title_user_id_field', 'categories', type_='unique')
    # ### end Alembic commands ###
