"""Add user_id for Alias

Revision ID: 68919bf9ca98
Revises: 01c02aec4745
Create Date: 2024-11-14 21:43:39.386165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68919bf9ca98'
down_revision: Union[str, None] = '01c02aec4745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aliases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aliases', type_='foreignkey')
    op.drop_column('aliases', 'user_id')
    # ### end Alembic commands ###
