"""Update Category.user_joined_date column

Revision ID: 9df2ae568c9f
Revises: adc98f5fc406
Create Date: 2024-12-03 22:40:54.761233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df2ae568c9f'
down_revision: Union[str, None] = 'adc98f5fc406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('joined_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_expenses', sa.JSON(), nullable=False),
    sa.Column('week_expenses', sa.JSON(), nullable=False),
    sa.Column('month_expenses', sa.JSON(), nullable=False),
    sa.Column('quarter_expenses', sa.JSON(), nullable=False),
    sa.Column('half_year_expenses', sa.JSON(), nullable=False),
    sa.Column('year_expenses', sa.JSON(), nullable=False),
    sa.Column('date_config_string', sa.String(), server_default=sa.text("concat(EXTRACT(doy FROM now()), '.', EXTRACT(week FROM now()), '.', EXTRACT(month FROM now()), '.', EXTRACT(quarter FROM now()), '.', CASE WHEN (EXTRACT(quarter FROM now()) < 3) THEN 1 ELSE 2 END, '.', EXTRACT(year FROM now()))"), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_joined_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings_options', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'aliases', ['id'])
    op.create_foreign_key(None, 'aliases', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aliases', type_='foreignkey')
    op.drop_constraint(None, 'aliases', type_='unique')
    op.drop_table('settings')
    op.drop_table('categories')
    op.drop_table('users')
    # ### end Alembic commands ###
