"""Add default value for Category.currency

Revision ID: 6b613f320c5f
Revises: 555b4d27aa49
Create Date: 2024-11-14 21:15:26.422777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b613f320c5f'
down_revision: Union[str, None] = '555b4d27aa49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
