"""Add timestamp for User and Category

Revision ID: bf1200ca4a10
Revises: 68919bf9ca98
Create Date: 2024-11-17 17:04:28.734851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1200ca4a10'
down_revision: Union[str, None] = '68919bf9ca98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aliases', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('categories', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('joined_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joined_date')
    op.drop_column('categories', 'timestamp')
    op.alter_column('aliases', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
