"""Edit category model

Revision ID: b9d1c858af98
Revises: b7f61cd3b5ca
Create Date: 2025-01-04 12:14:54.358613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9d1c858af98'
down_revision: Union[str, None] = 'b7f61cd3b5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'day_expenses',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.DECIMAL(),
                    existing_nullable=False)
    op.alter_column('categories', 'week_expenses',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.DECIMAL(),
                    existing_nullable=False)
    op.alter_column('categories', 'month_expenses',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.DECIMAL(),
                    existing_nullable=False)
    op.alter_column('categories', 'quarter_expenses',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.DECIMAL(),
                    existing_nullable=False)
    op.alter_column('categories', 'half_year_expenses',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.DECIMAL(),
                    existing_nullable=False)
    op.alter_column('categories', 'year_expenses',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.DECIMAL(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'year_expenses',
                    existing_type=sa.DECIMAL(),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=False)
    op.alter_column('categories', 'half_year_expenses',
                    existing_type=sa.DECIMAL(),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=False)
    op.alter_column('categories', 'quarter_expenses',
                    existing_type=sa.DECIMAL(),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=False)
    op.alter_column('categories', 'month_expenses',
                    existing_type=sa.DECIMAL(),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=False)
    op.alter_column('categories', 'week_expenses',
                    existing_type=sa.DECIMAL(),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=False)
    op.alter_column('categories', 'day_expenses',
                    existing_type=sa.DECIMAL(),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=False)
    # ### end Alembic commands ###
