"""Add user_id column to Alias model

Revision ID: 1bf88987cb88
Revises: b9d1c858af98
Create Date: 2025-01-04 15:48:36.843400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf88987cb88'
down_revision: Union[str, None] = 'b9d1c858af98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'aliases', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'aliases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'categories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'aliases', type_='foreignkey')
    op.drop_constraint(None, 'aliases', type_='foreignkey')
    op.drop_column('aliases', 'user_id')
    # ### end Alembic commands ###
